apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apisix
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: apisix
      finalizers:
        # This finalizer is for demo purposes, in production remove apps using argocd CLI "argocd app delete workload --cascade"
        # When you invoke argocd app delete with --cascade, the finalizer is added automatically.
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        # repoURL: 'https://omstots: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@github.com/sre-snsoft/SicBo-PROD.git'
        path: 'application-yml/apisix-sicbo/apisix'
        targetRevision: 'HEAD' #'{{metadata.annotations.workload_repo_revision}}'
        helm:
          valueFiles:
            - values-sicbo.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'ingress-apisix'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 60
